comp_shop/shop_v2/mainapp/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    CategoryDetailView,
    BaseView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckOutViews,
    MakeOrderView,
    RegisterUser,
)

urlpatterns = [
    path('', BaseView.as_view(), name="base"),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('category/<str:slug>', CategoryDetailView.as_view(), name="category_detail"),
    path('cart/', CartView.as_view(), name="cart"),
    path('add_to_cart/<str:ct_model>/<str:slug>', AddToCartView.as_view(), name="add_to_cart"),
    path('remove_from_cart/<str:ct_model>/<str:slug>', DeleteFromCartView.as_view(), name="delete_from_cart"),
    path('change_qty/<str:ct_model>/<str:slug>', ChangeQTYView.as_view(), name="change_qty"),
    path('checkout/', CheckOutViews.as_view(), name="checkout"),
    path('make_order/', MakeOrderView.as_view(), name="make_order"),
    path('register/', RegisterUser.as_view(), name="register"),
]

comp_shop/shop_v2/shop_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("mainapp.urls")),
    # Автоматический редирект на страницу shop/
    path('', RedirectView.as_view(url='shop/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

comp_shop/shop_v2/mainapp/models.py
from PIL import Image
from io import BytesIO
from django.db import models
from django.contrib.auth import get_user_model
# ContentType - мини фреймворк, который видит все модели из приложений, которые есть в Installed_apps в settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.core.files import File
from django.urls import reverse
from django.utils import timezone

# Параметры берутся из settings.AUTH_USER_MODEL (само поле скрыто, но есть значения по умолчанию)
User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viename):
    """Получение url адреса модели"""
    # Получает имя модели
    ct_model = obj.__class__._meta.model_name
    return reverse(viename, kwargs={"ct_model": ct_model, "slug": obj.slug})


class LatestProductsManager:
    """Очень сомнительный класс, следует переписать код в файле view применяя пагинатор"""

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get("with_respect_to")
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__.meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):
    """Менеджер категорий"""
    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    """Продукт"""
    category = models.ForeignKey("Category", verbose_name="Категория", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Наименование")
    slug = models.SlugField(unique=True, verbose_name='URL')
    image = models.ImageField(verbose_name="Изображение",
                              help_text="<b style='color:red; font-size:16px';>Загружайте изображение разрешением минимум 400х400</b>")
    description = models.TextField(verbose_name="Описание товара", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")

    def __str__(self):
        return self.title

    def get_model_name(self):
        # Вызваем у удаляемого объекта имя модели
        return self.__class__.__name__.lower()

    def clean(self):
        """Проверка размера изображения"""
        if not self.image:
            raise ValidationError("Требуется загрузить изображение")
        else:
            w, h = get_image_dimensions(self.image)
            if w <= 400:
                raise ValidationError(f"Требуемое разрешения для загрузки от 400. У текущего изображения{w} ")
            if h <= 400:
                raise ValidationError(f"Требуемое разрешения для загрузки от 400. У текущего изображения{h} ")

    def make_thumbnail(self, image, size=(500, 500)):
        """Сохранение изображения"""
        img = Image.open(self.image)
        if img.height > 500 or img.width > 500:
            img.convert('RGB')  # Конвертируем изображение в дружественный для Pillow формат
            img.thumbnail(size)  # Меняем разрешение изображения
            thumb_io = BytesIO()  # Создаём BytesIO objects
            img.save(thumb_io, 'JPEG', quality=25)  # Сохраняем изображение в виде BytesIO объекта
            thumbnail = File(thumb_io, name=self.image.name)
            return thumbnail

    class Meta:
        abstract = True


class Notebook(Product):
    """Ноутбуки"""
    diagonal = models.CharField(max_length=50, verbose_name="Диагональ")
    display_type = models.CharField(max_length=50, verbose_name="Тип дисплэя")
    resolution = models.CharField(max_length=100, verbose_name="Разрешение экрана")
    processor_freq = models.CharField(max_length=50, verbose_name="Частота процессора")
    ram = models.CharField(max_length=100, verbose_name="Оперативная память")
    video = models.CharField(max_length=100, verbose_name="Видеокарта")
    time_without_charge = models.CharField(max_length=50, verbose_name="Время работы от аккумулятора")

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    """Смартфоны"""
    diagonal = models.CharField(max_length=50, verbose_name="Диагональ")
    display_type = models.CharField(max_length=50, verbose_name="Тип дисплэя")
    resolution = models.CharField(max_length=100, verbose_name="Разрешение экрана")
    accum_volume = models.CharField(max_length=100, verbose_name="Объем аккумулятора")
    ram = models.CharField(max_length=100, verbose_name="Оперативная память")
    # Возможность добавлять внешнюю память
    sd = models.BooleanField(verbose_name='Наличие SD карты', default=True)
    # Переделать с использованием choice поля
    sd_volume_max = models.CharField(max_length=100, verbose_name="Максимальный объем встраиваемой памяти", null=True,
                                     blank=True)
    main_cam_mp = models.CharField(max_length=20, verbose_name="Главная камера")
    frontal_cam_mp = models.CharField(max_length=20, verbose_name="Фронтальная камера")

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):
    """Заглушка - продукт корзины"""
    user = models.ForeignKey("Customer", verbose_name="Покупатель", on_delete=models.CASCADE)
    cart = models.ForeignKey("Cart", verbose_name="Корзина", on_delete=models.CASCADE, related_name="related_products")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    # Автоматически заполнит поля content_type и object_id
    content_object = GenericForeignKey("content_type", "object_id")
    # Количество
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая стоимость", default=0)

    def __str__(self):
        return f"Продукт: {self.content_object}"

    def save(self, *args, **kwargs):
        # Вычисление финальной цены на основании количества товара
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)

    def get_model_name(self):
        # Вызваем у удаляемого объекта имя модели
        return self.content_object._meta.model_name


class Cart(models.Model):
    """Корзина"""
    owner = models.ForeignKey("Customer", verbose_name="Владелец", on_delete=models.CASCADE, null=True)
    products = models.ManyToManyField("CartProduct", blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая стоимость", default=0)
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return f"ID корзины: {self.id} {self.owner}"




class Customer(models.Model):
    """Покупатель"""
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name="Телефон", null=True)
    address = models.CharField(max_length=255, verbose_name="Адрес", null=True)
    orders = models.ManyToManyField('Order', verbose_name="Заказы покупателя", related_name='related_customer')

    def __str__(self):
        return f"Покупатель: {self.user.first_name} {self.user.last_name}"


class Order(models.Model):
    """Заказ"""

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Заказ на самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Заказ с доставкой'),
    )

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ завершён'),
    )

    customer = models.ForeignKey(Customer, verbose_name="Покупатель", related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    phone = models.CharField(max_length=28, verbose_name="Номер телефона")

comp_shop/shop_v2/mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Order


class OrderForm(forms.ModelForm):
    """Форма заказа"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order

        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment',
        )

class RegisterUserForm(UserCreationForm):
    """Форма регистрации пользователя"""
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Введите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')
        widgets = {
            'username': forms.TextInput(),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
        }

# class AuthUserForm(AuthenticationForm):
#     """Форма входа пользователя"""
#     username = forms.CharField(label='Введите имя пользователя: ', widget=forms.TextInput(attrs={'class': 'form-input'}))
#     password = forms.CharField(label='Введите пароль для входа: ', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
#
#     class Meta:
#         model = User
#         fields = ('username', 'password1')
#         widgets = {
#             'username': forms.TextInput(),
#             'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
#         }

comp_shop/shop_v2/mainapp/templates/mainapp/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>

{% endblock %}

comp_shop/shop_v2/mainapp/templates/mainapp/cart.html
{% extends 'layout/base.html' %}

{% block content %}

<!--Обращаемся через cart к products-->
<h3>Ваша корзина: {% if not cart.products.count %} пуста {% endif %}</h3>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">Наименование</th>
        <th scope="col">Изображение</th>
        <th scope="col">Цена</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
        <th scope="col">Действие</th>
    </tr>
    </thead>
    {% for item in cart.products.all %}
    <tbody>
    <tr>
        <td><a href="{% url 'product_detail' ct_model=item.get_model_name slug=item.content_object.slug %}">{{ item.content_object.title }}</a></td>
        <td><img width="200px" height="200px" class="img-thumbnail" src="{{ item.content_object.image.url }}"></td>
        <td>{{ item.content_object.price }}</td>
        <td>
            <form action="{% url 'change_qty' ct_model=item.get_model_name slug=item.content_object.slug %}" method="post">
                {% csrf_token %}
                <input name="qty" style="width: 50px" min="1" type="number" value="{{ item.qty }}">
                <br>
                <input class="btn btn-dark" type="submit" class="btn btn-primary" value="Изменить количество">
            </form>
        </td>
        <td><strong>{{ item.final_price }} руб.</strong></td>
        <td>
            <a href="{% url 'delete_from_cart' ct_model=item.get_model_name slug=item.content_object.slug %}">
                <button class="btn btn-outline-dark flex-shrink-0" type="button">
                    <i class="bi-cart-fill me-1"></i>
                    Удалить из корзины
                </button>
            </a>
        </td>
    </tr>
    </tbody>
    {% endfor %}
    <tr>
        <td colspan="2"></td>
        <td>Итого:</td>
        <td>{{ cart.total_products }}</td>
        <td><strong>{{ cart.final_price }} руб.</strong></td>
        <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению заказа</button></a></td>
    </tr>
</table>
{% endif %}

{% endblock content %}

comp_shop/shop_v2/mainapp/templates/mainapp/category_detail.html
{% extends 'layout/base.html' %}


{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item">{{ category.name }}</li>
    </ol>
</nav>
</div>
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <section class="py-5">
        <div class="container mt-5">
            {% for product in category_products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <a href="{{ product.get_absolute_url }}"> <img style="width: 300px; height: 300px"
                                                                   class="card-img-top" src="{{ product.image.url }}"
                                                                   alt="..."/></a>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <a href="{{ product.get_absolute_url }}"> {{ product.title }}</a>
                            <!-- Product price-->
                            <h5>{{ product.price }} руб</h5>
                            <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                                <button class="btn btn-danger">Добавить в корзину</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</div>
</div>

{% endblock content %}

comp_shop/shop_v2/mainapp/templates/mainapp/checkout.html
{% extends 'layout/base.html' %}
<!--Библиотека django-crispy-forms-->
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>{{ item.qty }}</td>
            <td>{{ item.final_price }} руб.</td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
        </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
<!--  Используется из библиотеки django-crispy-forms-->
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block mb-3" values="Оформить заказ">
</form>
{% endblock content %}

comp_shop/shop_v2/mainapp/templates/mainapp/checkout_not_ready.html
{% extends 'layout/base.html' %}

{% block content %}


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Checkout example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/checkout/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
  </head>
  <body class="bg-light">

<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Checkout form</h2>
      <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">3</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Product name</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$12</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Second product</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$8</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Third item</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$20</strong>
          </li>
        </ul>

        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" class="form-control" id="username" placeholder="Username" required>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required>
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required>
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
          </div>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cc-name" class="form-label">Name on card</label>
              <input type="text" class="form-control" id="cc-name" placeholder="" required>
              <small class="text-muted">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div>
            </div>

            <div class="col-md-6">
              <label for="cc-number" class="form-label">Credit card number</label>
              <input type="text" class="form-control" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
                Credit card number is required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">Expiration</label>
              <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                Expiration date required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-cvv" class="form-label">CVV</label>
              <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
              <div class="invalid-feedback">
                Security code required
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>



    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      <script src="form-validation.js"></script>
  </body>
</html>


{% endblock content %}